### ISSUE TITLE
Introduction links to Error 404 page

### ISSUE THREAD

**Issue by yanzhe-chen** [GitbookIO/documentation#17]
Steps to reproduce this problem:

1. Open http://help.gitbook.io
2. Click **Introduction** in the **Summary** section
3. It jumps to http://help.gitbook.io/README.html, which is an **Error 404** page

**Comment by neomatrix369** [comment]
I have reported a similar problem when the url ends with the text null, so my urls are looking like this  http://help.gitbook.io/README.htmlnull.

**Comment by SamyPesse** [comment]
Fixed, same as https://github.com/GitbookIO/gitbook/issues/651
